# Generated by Django 3.2.4 on 2021-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtypes',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
