# Generated by Django 3.2.4 on 2021-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_alter_mymeal_mealdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymeal',
            name='totalCalosPerMeal',
            field=models.FloatField(),
        ),
    ]
