# Generated by Django 3.2.4 on 2021-07-13 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal', '0007_alter_mymeal_totalcalospermeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymeal',
            name='totalCalosPerMeal',
        ),
        migrations.CreateModel(
            name='totalCalosPerMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calos', models.FloatField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.mymeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
