# Generated by Django 3.2.4 on 2021-07-13 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_auto_20210713_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcalospermeal',
            name='dateOfMeal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
