# Generated by Django 3.2.4 on 2021-07-14 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0010_totalcalosperday'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcalosperday',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
