# Generated by Django 3.2.4 on 2021-07-06 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodystats', '0003_auto_20210706_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodystatus',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(18)]),
        ),
    ]
