# Generated by Django 3.2.4 on 2021-07-07 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodystats', '0005_alter_bodystatus_totoalcaloriesperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodystatus',
            name='hiegth',
            field=models.IntegerField(default=160, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(160)]),
        ),
        migrations.AlterField(
            model_name='bodystatus',
            name='weight',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(60)]),
        ),
    ]
