# Generated by Django 3.2.4 on 2021-07-15 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodystats', '0006_auto_20210707_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodystatus',
            name='female',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bodystatus',
            name='weight',
            field=models.IntegerField(default=40, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(40)]),
        ),
    ]
